// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    actor_id,
    action,
    target_type,
    target_id,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id
`

type CreateAuditLogParams struct {
	ActorID    uuid.NullUUID         `json:"actor_id"`
	Action     string                `json:"action"`
	TargetType string                `json:"target_type"`
	TargetID   uuid.NullUUID         `json:"target_id"`
	Payload    pqtype.NullRawMessage `json:"payload"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
