// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: loan_items.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveLoanItemReturn = `-- name: ApproveLoanItemReturn :exec
UPDATE loan_items
SET return_approved_at = $2,
    return_approved_by = $3,
    updated_at = NOW()
WHERE id = $1
`

type ApproveLoanItemReturnParams struct {
	ID               uuid.UUID     `json:"id"`
	ReturnApprovedAt sql.NullTime  `json:"return_approved_at"`
	ReturnApprovedBy uuid.NullUUID `json:"return_approved_by"`
}

func (q *Queries) ApproveLoanItemReturn(ctx context.Context, arg ApproveLoanItemReturnParams) error {
	_, err := q.db.ExecContext(ctx, approveLoanItemReturn, arg.ID, arg.ReturnApprovedAt, arg.ReturnApprovedBy)
	return err
}

const createLoanItem = `-- name: CreateLoanItem :one
INSERT INTO loan_items (
    box_id,
    tool_id,
    borrower_id,
    start_date,
    due_date,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, box_id, tool_id, borrower_id, start_date, due_date, return_requested_at, return_requested_by, return_approved_at, return_approved_by, created_at, updated_at
`

type CreateLoanItemParams struct {
	BoxID      uuid.UUID `json:"box_id"`
	ToolID     uuid.UUID `json:"tool_id"`
	BorrowerID uuid.UUID `json:"borrower_id"`
	StartDate  time.Time `json:"start_date"`
	DueDate    time.Time `json:"due_date"`
}

func (q *Queries) CreateLoanItem(ctx context.Context, arg CreateLoanItemParams) (LoanItem, error) {
	row := q.db.QueryRowContext(ctx, createLoanItem,
		arg.BoxID,
		arg.ToolID,
		arg.BorrowerID,
		arg.StartDate,
		arg.DueDate,
	)
	var i LoanItem
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.ToolID,
		&i.BorrowerID,
		&i.StartDate,
		&i.DueDate,
		&i.ReturnRequestedAt,
		&i.ReturnRequestedBy,
		&i.ReturnApprovedAt,
		&i.ReturnApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanItemForUpdate = `-- name: GetLoanItemForUpdate :one
SELECT id, box_id, tool_id, borrower_id, start_date, due_date, return_requested_at, return_requested_by, return_approved_at, return_approved_by, created_at, updated_at
FROM loan_items
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetLoanItemForUpdate(ctx context.Context, id uuid.UUID) (LoanItem, error) {
	row := q.db.QueryRowContext(ctx, getLoanItemForUpdate, id)
	var i LoanItem
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.ToolID,
		&i.BorrowerID,
		&i.StartDate,
		&i.DueDate,
		&i.ReturnRequestedAt,
		&i.ReturnRequestedBy,
		&i.ReturnApprovedAt,
		&i.ReturnApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanItemInBoxForUpdate = `-- name: GetLoanItemInBoxForUpdate :one
SELECT id, box_id, tool_id, borrower_id, start_date, due_date, return_requested_at, return_requested_by, return_approved_at, return_approved_by, created_at, updated_at
FROM loan_items
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetLoanItemInBoxForUpdate(ctx context.Context, id uuid.UUID) (LoanItem, error) {
	row := q.db.QueryRowContext(ctx, getLoanItemInBoxForUpdate, id)
	var i LoanItem
	err := row.Scan(
		&i.ID,
		&i.BoxID,
		&i.ToolID,
		&i.BorrowerID,
		&i.StartDate,
		&i.DueDate,
		&i.ReturnRequestedAt,
		&i.ReturnRequestedBy,
		&i.ReturnApprovedAt,
		&i.ReturnApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasFutureReservationByOther = `-- name: HasFutureReservationByOther :one
SELECT EXISTS (
    SELECT 1
    FROM loan_items li
    WHERE li.tool_id = $1
      AND li.return_approved_at IS NULL
      AND li.start_date > $2::date
      AND li.borrower_id <> $3
) AS exists
`

type HasFutureReservationByOtherParams struct {
	ToolID     uuid.UUID `json:"tool_id"`
	Column2    time.Time `json:"column_2"`
	BorrowerID uuid.UUID `json:"borrower_id"`
}

func (q *Queries) HasFutureReservationByOther(ctx context.Context, arg HasFutureReservationByOtherParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasFutureReservationByOther, arg.ToolID, arg.Column2, arg.BorrowerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasOverlappingLoanItem = `-- name: HasOverlappingLoanItem :one
SELECT EXISTS (
    SELECT 1
    FROM loan_items li
    WHERE li.tool_id = $1
      AND li.return_approved_at IS NULL
      AND daterange(li.start_date, li.due_date, '[]') && daterange($2::date, $3::date, '[]')
) AS exists
`

type HasOverlappingLoanItemParams struct {
	ToolID  uuid.UUID `json:"tool_id"`
	Column2 time.Time `json:"column_2"`
	Column3 time.Time `json:"column_3"`
}

func (q *Queries) HasOverlappingLoanItem(ctx context.Context, arg HasOverlappingLoanItemParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasOverlappingLoanItem, arg.ToolID, arg.Column2, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMyOpenLoanItems = `-- name: ListMyOpenLoanItems :many
SELECT
    li.id,
    li.box_id,
    lb.display_name AS box_display_name,
    li.tool_id,
    t.asset_no,
    t.name AS tool_name,
    li.start_date,
    li.due_date,
    li.return_requested_at,
    li.return_approved_at
FROM loan_items li
JOIN loan_boxes lb ON lb.id = li.box_id
JOIN tools t ON t.id = li.tool_id
WHERE li.borrower_id = $1
  AND li.return_approved_at IS NULL
ORDER BY li.start_date ASC, li.created_at ASC
`

type ListMyOpenLoanItemsRow struct {
	ID                uuid.UUID    `json:"id"`
	BoxID             uuid.UUID    `json:"box_id"`
	BoxDisplayName    string       `json:"box_display_name"`
	ToolID            uuid.UUID    `json:"tool_id"`
	AssetNo           string       `json:"asset_no"`
	ToolName          string       `json:"tool_name"`
	StartDate         time.Time    `json:"start_date"`
	DueDate           time.Time    `json:"due_date"`
	ReturnRequestedAt sql.NullTime `json:"return_requested_at"`
	ReturnApprovedAt  sql.NullTime `json:"return_approved_at"`
}

func (q *Queries) ListMyOpenLoanItems(ctx context.Context, borrowerID uuid.UUID) ([]ListMyOpenLoanItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyOpenLoanItems, borrowerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOpenLoanItemsRow{}
	for rows.Next() {
		var i ListMyOpenLoanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoxID,
			&i.BoxDisplayName,
			&i.ToolID,
			&i.AssetNo,
			&i.ToolName,
			&i.StartDate,
			&i.DueDate,
			&i.ReturnRequestedAt,
			&i.ReturnApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueLoanItems = `-- name: ListOverdueLoanItems :many
SELECT
    li.id AS loan_item_id,
    li.box_id,
    lb.display_name AS box_display_name,
    li.tool_id,
    t.asset_no,
    t.name AS tool_name,
    li.start_date,
    li.due_date,
    u.id AS borrower_id,
    u.username AS borrower_username,
    u.email AS borrower_email
FROM loan_items li
JOIN loan_boxes lb ON lb.id = li.box_id
JOIN tools t ON t.id = li.tool_id
JOIN users u ON u.id = li.borrower_id
WHERE li.return_approved_at IS NULL
  AND li.start_date <= $1::date
  AND li.due_date < $1::date
ORDER BY u.username ASC, li.due_date ASC
`

type ListOverdueLoanItemsRow struct {
	LoanItemID       uuid.UUID `json:"loan_item_id"`
	BoxID            uuid.UUID `json:"box_id"`
	BoxDisplayName   string    `json:"box_display_name"`
	ToolID           uuid.UUID `json:"tool_id"`
	AssetNo          string    `json:"asset_no"`
	ToolName         string    `json:"tool_name"`
	StartDate        time.Time `json:"start_date"`
	DueDate          time.Time `json:"due_date"`
	BorrowerID       uuid.UUID `json:"borrower_id"`
	BorrowerUsername string    `json:"borrower_username"`
	BorrowerEmail    string    `json:"borrower_email"`
}

func (q *Queries) ListOverdueLoanItems(ctx context.Context, dollar_1 time.Time) ([]ListOverdueLoanItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueLoanItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueLoanItemsRow{}
	for rows.Next() {
		var i ListOverdueLoanItemsRow
		if err := rows.Scan(
			&i.LoanItemID,
			&i.BoxID,
			&i.BoxDisplayName,
			&i.ToolID,
			&i.AssetNo,
			&i.ToolName,
			&i.StartDate,
			&i.DueDate,
			&i.BorrowerID,
			&i.BorrowerUsername,
			&i.BorrowerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestedItemsInBoxForUpdate = `-- name: ListPendingRequestedItemsInBoxForUpdate :many
SELECT id, box_id, tool_id, borrower_id, start_date, due_date, return_requested_at, return_requested_by, return_approved_at, return_approved_by, created_at, updated_at
FROM loan_items
WHERE box_id = $1
  AND return_requested_at IS NOT NULL
  AND return_approved_at IS NULL
FOR UPDATE
`

func (q *Queries) ListPendingRequestedItemsInBoxForUpdate(ctx context.Context, boxID uuid.UUID) ([]LoanItem, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRequestedItemsInBoxForUpdate, boxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoanItem{}
	for rows.Next() {
		var i LoanItem
		if err := rows.Scan(
			&i.ID,
			&i.BoxID,
			&i.ToolID,
			&i.BorrowerID,
			&i.StartDate,
			&i.DueDate,
			&i.ReturnRequestedAt,
			&i.ReturnRequestedBy,
			&i.ReturnApprovedAt,
			&i.ReturnApprovedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnRequestRows = `-- name: ListReturnRequestRows :many
SELECT
    lb.id AS box_id,
    lb.display_name AS box_display_name,
    lb.start_date AS box_start_date,
    lb.due_date AS box_due_date,
    u.username AS borrower_username,
    li.id AS loan_item_id,
    li.tool_id,
    t.asset_no,
    t.name AS tool_name,
    li.start_date,
    li.due_date,
    li.return_requested_at
FROM loan_items li
JOIN loan_boxes lb ON lb.id = li.box_id
JOIN users u ON u.id = li.borrower_id
JOIN tools t ON t.id = li.tool_id
WHERE li.return_requested_at IS NOT NULL
  AND li.return_approved_at IS NULL
ORDER BY lb.created_at ASC, li.created_at ASC
`

type ListReturnRequestRowsRow struct {
	BoxID             uuid.UUID    `json:"box_id"`
	BoxDisplayName    string       `json:"box_display_name"`
	BoxStartDate      time.Time    `json:"box_start_date"`
	BoxDueDate        time.Time    `json:"box_due_date"`
	BorrowerUsername  string       `json:"borrower_username"`
	LoanItemID        uuid.UUID    `json:"loan_item_id"`
	ToolID            uuid.UUID    `json:"tool_id"`
	AssetNo           string       `json:"asset_no"`
	ToolName          string       `json:"tool_name"`
	StartDate         time.Time    `json:"start_date"`
	DueDate           time.Time    `json:"due_date"`
	ReturnRequestedAt sql.NullTime `json:"return_requested_at"`
}

func (q *Queries) ListReturnRequestRows(ctx context.Context) ([]ListReturnRequestRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReturnRequestRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReturnRequestRowsRow{}
	for rows.Next() {
		var i ListReturnRequestRowsRow
		if err := rows.Scan(
			&i.BoxID,
			&i.BoxDisplayName,
			&i.BoxStartDate,
			&i.BoxDueDate,
			&i.BorrowerUsername,
			&i.LoanItemID,
			&i.ToolID,
			&i.AssetNo,
			&i.ToolName,
			&i.StartDate,
			&i.DueDate,
			&i.ReturnRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLoanItemReturnRequested = `-- name: MarkLoanItemReturnRequested :exec
UPDATE loan_items
SET return_requested_at = $2,
    return_requested_by = $3,
    updated_at = NOW()
WHERE id = $1
`

type MarkLoanItemReturnRequestedParams struct {
	ID                uuid.UUID     `json:"id"`
	ReturnRequestedAt sql.NullTime  `json:"return_requested_at"`
	ReturnRequestedBy uuid.NullUUID `json:"return_requested_by"`
}

func (q *Queries) MarkLoanItemReturnRequested(ctx context.Context, arg MarkLoanItemReturnRequestedParams) error {
	_, err := q.db.ExecContext(ctx, markLoanItemReturnRequested, arg.ID, arg.ReturnRequestedAt, arg.ReturnRequestedBy)
	return err
}
