// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: loan_boxes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLoanBox = `-- name: CreateLoanBox :one
INSERT INTO loan_boxes (
    borrower_id,
    box_no,
    display_name,
    start_date,
    due_date,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
RETURNING id, borrower_id, box_no, display_name, start_date, due_date, created_at, updated_at
`

type CreateLoanBoxParams struct {
	BorrowerID  uuid.UUID `json:"borrower_id"`
	BoxNo       int32     `json:"box_no"`
	DisplayName string    `json:"display_name"`
	StartDate   time.Time `json:"start_date"`
	DueDate     time.Time `json:"due_date"`
}

func (q *Queries) CreateLoanBox(ctx context.Context, arg CreateLoanBoxParams) (LoanBox, error) {
	row := q.db.QueryRowContext(ctx, createLoanBox,
		arg.BorrowerID,
		arg.BoxNo,
		arg.DisplayName,
		arg.StartDate,
		arg.DueDate,
	)
	var i LoanBox
	err := row.Scan(
		&i.ID,
		&i.BorrowerID,
		&i.BoxNo,
		&i.DisplayName,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanBoxByID = `-- name: GetLoanBoxByID :one
SELECT id, borrower_id, box_no, display_name, start_date, due_date, created_at, updated_at
FROM loan_boxes
WHERE id = $1
`

func (q *Queries) GetLoanBoxByID(ctx context.Context, id uuid.UUID) (LoanBox, error) {
	row := q.db.QueryRowContext(ctx, getLoanBoxByID, id)
	var i LoanBox
	err := row.Scan(
		&i.ID,
		&i.BorrowerID,
		&i.BoxNo,
		&i.DisplayName,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxBorrowerBoxNo = `-- name: GetMaxBorrowerBoxNo :one
SELECT COALESCE(MAX(box_no), 0)::int AS max_box_no
FROM loan_boxes
WHERE borrower_id = $1
`

func (q *Queries) GetMaxBorrowerBoxNo(ctx context.Context, borrowerID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxBorrowerBoxNo, borrowerID)
	var max_box_no int32
	err := row.Scan(&max_box_no)
	return max_box_no, err
}
