// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	Action     string                `json:"action"`
	TargetType string                `json:"target_type"`
	TargetID   uuid.NullUUID         `json:"target_id"`
	Payload    pqtype.NullRawMessage `json:"payload"`
	CreatedAt  time.Time             `json:"created_at"`
}

type LoanBox struct {
	ID          uuid.UUID `json:"id"`
	BorrowerID  uuid.UUID `json:"borrower_id"`
	BoxNo       int32     `json:"box_no"`
	DisplayName string    `json:"display_name"`
	StartDate   time.Time `json:"start_date"`
	DueDate     time.Time `json:"due_date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type LoanItem struct {
	ID                uuid.UUID     `json:"id"`
	BoxID             uuid.UUID     `json:"box_id"`
	ToolID            uuid.UUID     `json:"tool_id"`
	BorrowerID        uuid.UUID     `json:"borrower_id"`
	StartDate         time.Time     `json:"start_date"`
	DueDate           time.Time     `json:"due_date"`
	ReturnRequestedAt sql.NullTime  `json:"return_requested_at"`
	ReturnRequestedBy uuid.NullUUID `json:"return_requested_by"`
	ReturnApprovedAt  sql.NullTime  `json:"return_approved_at"`
	ReturnApprovedBy  uuid.NullUUID `json:"return_approved_by"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type Tool struct {
	ID          uuid.UUID      `json:"id"`
	AssetNo     string         `json:"asset_no"`
	TagID       sql.NullString `json:"tag_id"`
	Name        string         `json:"name"`
	WarehouseID uuid.UUID      `json:"warehouse_id"`
	BaseStatus  string         `json:"base_status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Role         string    `json:"role"`
	Department   string    `json:"department"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Warehouse struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Reservation struct {
	ID            uuid.UUID `json:"id"`
	ToolID        uuid.UUID `json:"tool_id"`
	OwnerUsername string    `json:"owner_username"`
	StartDate     time.Time `json:"start_date"`
	DueDate       time.Time `json:"due_date"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}
