// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveLoanItemReturn(ctx context.Context, arg ApproveLoanItemReturnParams) error
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountToolsWithDisplay(ctx context.Context, arg CountToolsWithDisplayParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (uuid.UUID, error)
	CreateLoanBox(ctx context.Context, arg CreateLoanBoxParams) (LoanBox, error)
	CreateLoanItem(ctx context.Context, arg CreateLoanItemParams) (LoanItem, error)
	CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWarehouse(ctx context.Context, name string) (Warehouse, error)
	GetLoanBoxByID(ctx context.Context, id uuid.UUID) (LoanBox, error)
	GetLoanItemForUpdate(ctx context.Context, id uuid.UUID) (LoanItem, error)
	GetLoanItemInBoxForUpdate(ctx context.Context, id uuid.UUID) (LoanItem, error)
	GetMaxBorrowerBoxNo(ctx context.Context, borrowerID uuid.UUID) (int32, error)
	GetToolByID(ctx context.Context, id uuid.UUID) (Tool, error)
	GetToolByTag(ctx context.Context, tagID sql.NullString) (Tool, error)
	GetToolForUpdate(ctx context.Context, id uuid.UUID) (Tool, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByLoginID(ctx context.Context, email string) (GetUserByLoginIDRow, error)
	HasFutureReservationByOther(ctx context.Context, arg HasFutureReservationByOtherParams) (bool, error)
	HasOverlappingLoanItem(ctx context.Context, arg HasOverlappingLoanItemParams) (bool, error)
	ListAdminEmails(ctx context.Context) ([]string, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListMyOpenLoanItems(ctx context.Context, borrowerID uuid.UUID) ([]ListMyOpenLoanItemsRow, error)
	ListOverdueLoanItems(ctx context.Context, dollar_1 time.Time) ([]ListOverdueLoanItemsRow, error)
	ListPendingRequestedItemsInBoxForUpdate(ctx context.Context, boxID uuid.UUID) ([]LoanItem, error)
	ListReturnRequestRows(ctx context.Context) ([]ListReturnRequestRowsRow, error)
	ListToolsWithDisplay(ctx context.Context, arg ListToolsWithDisplayParams) ([]ListToolsWithDisplayRow, error)
	ListWarehouses(ctx context.Context) ([]Warehouse, error)
	LockUserForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	MarkLoanItemReturnRequested(ctx context.Context, arg MarkLoanItemReturnRequestedParams) error
	UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error)
	UpdateToolTag(ctx context.Context, arg UpdateToolTagParams) (Tool, error)
}

var _ Querier = (*Queries)(nil)
