// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tools.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countToolsWithDisplay = `-- name: CountToolsWithDisplay :one
WITH tool_state AS (
    SELECT
        t.id,
        t.asset_no,
        t.name,
        t.warehouse_id,
        w.name AS warehouse_name,
        t.base_status,
        loan.start_date AS loan_start_date,
        loan.due_date AS loan_due_date,
        reserve.start_date AS reserved_start_date,
        reserve.due_date AS reserved_due_date,
        reserve.borrower_id AS reserved_by
    FROM tools t
    JOIN warehouses w ON w.id = t.warehouse_id
    LEFT JOIN LATERAL (
        SELECT li.start_date, li.due_date, li.borrower_id
        FROM loan_items li
        WHERE li.tool_id = t.id
          AND li.return_approved_at IS NULL
          AND li.start_date <= $1::date
        ORDER BY li.start_date DESC
        LIMIT 1
    ) AS loan ON TRUE
    LEFT JOIN LATERAL (
        SELECT li.start_date, li.due_date, li.borrower_id
        FROM loan_items li
        WHERE li.tool_id = t.id
          AND li.return_approved_at IS NULL
          AND li.start_date > $1::date
        ORDER BY li.start_date ASC
        LIMIT 1
    ) AS reserve ON TRUE
    WHERE
        (NULLIF($2::text, '') IS NULL OR t.warehouse_id = NULLIF($2::text, '')::uuid)
        AND (
            $3::text = ''
            OR (
                CASE
                    WHEN $4::text = 'exact' THEN (t.name = $3::text OR t.asset_no = $3::text)
                    ELSE (t.name ILIKE '%' || $3::text || '%' OR t.asset_no ILIKE '%' || $3::text || '%')
                END
            )
        )
)
SELECT COUNT(*)::bigint AS total
FROM tool_state
WHERE
    (
        $5::text = ''
        OR (
            CASE
                WHEN base_status = 'BROKEN' THEN 'BROKEN'
                WHEN base_status = 'REPAIR' THEN 'REPAIR'
                WHEN loan_start_date IS NOT NULL THEN 'LOANED'
                WHEN reserved_start_date IS NOT NULL THEN 'RESERVED'
                ELSE 'AVAILABLE'
            END = $5::text
        )
    )
`

type CountToolsWithDisplayParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 string    `json:"column_4"`
	Column5 string    `json:"column_5"`
}

func (q *Queries) CountToolsWithDisplay(ctx context.Context, arg CountToolsWithDisplayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countToolsWithDisplay,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTool = `-- name: CreateTool :one
INSERT INTO tools (
    asset_no,
    name,
    warehouse_id,
    base_status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW()
)
RETURNING id, asset_no, name, warehouse_id, base_status, created_at, updated_at
`

type CreateToolParams struct {
	AssetNo     string    `json:"asset_no"`
	Name        string    `json:"name"`
	WarehouseID uuid.UUID `json:"warehouse_id"`
	BaseStatus  string    `json:"base_status"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRowContext(ctx, createTool,
		arg.AssetNo,
		arg.Name,
		arg.WarehouseID,
		arg.BaseStatus,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.WarehouseID,
		&i.BaseStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolByID = `-- name: GetToolByID :one
SELECT id, asset_no, name, warehouse_id, base_status, created_at, updated_at
FROM tools
WHERE id = $1
`

func (q *Queries) GetToolByID(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRowContext(ctx, getToolByID, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.WarehouseID,
		&i.BaseStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolForUpdate = `-- name: GetToolForUpdate :one
SELECT id, asset_no, name, warehouse_id, base_status, created_at, updated_at
FROM tools
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetToolForUpdate(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRowContext(ctx, getToolForUpdate, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.WarehouseID,
		&i.BaseStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listToolsWithDisplay = `-- name: ListToolsWithDisplay :many
WITH tool_state AS (
    SELECT
        t.id,
        t.asset_no,
        t.name,
        t.warehouse_id,
        w.name AS warehouse_name,
        t.base_status,
        loan.start_date AS loan_start_date,
        loan.due_date AS loan_due_date,
        reserve.start_date AS reserved_start_date,
        reserve.due_date AS reserved_due_date,
        reserve.borrower_id AS reserved_by
    FROM tools t
    JOIN warehouses w ON w.id = t.warehouse_id
    LEFT JOIN LATERAL (
        SELECT li.start_date, li.due_date, li.borrower_id
        FROM loan_items li
        WHERE li.tool_id = t.id
          AND li.return_approved_at IS NULL
          AND li.start_date <= $1::date
        ORDER BY li.start_date DESC
        LIMIT 1
    ) AS loan ON TRUE
    LEFT JOIN LATERAL (
        SELECT li.start_date, li.due_date, li.borrower_id
        FROM loan_items li
        WHERE li.tool_id = t.id
          AND li.return_approved_at IS NULL
          AND li.start_date > $1::date
        ORDER BY li.start_date ASC
        LIMIT 1
    ) AS reserve ON TRUE
    WHERE
        (NULLIF($2::text, '') IS NULL OR t.warehouse_id = NULLIF($2::text, '')::uuid)
        AND (
            $3::text = ''
            OR (
                CASE
                    WHEN $4::text = 'exact' THEN (t.name = $3::text OR t.asset_no = $3::text)
                    ELSE (t.name ILIKE '%' || $3::text || '%' OR t.asset_no ILIKE '%' || $3::text || '%')
                END
            )
        )
)
SELECT
    id,
    asset_no,
    name,
    warehouse_id,
    warehouse_name,
    base_status,
    CASE
        WHEN base_status = 'BROKEN' THEN 'BROKEN'
        WHEN base_status = 'REPAIR' THEN 'REPAIR'
        WHEN loan_start_date IS NOT NULL THEN 'LOANED'
        WHEN reserved_start_date IS NOT NULL THEN 'RESERVED'
        ELSE 'AVAILABLE'
    END AS display_status,
    CASE
        WHEN loan_start_date IS NOT NULL THEN loan_start_date
        ELSE reserved_start_date
    END AS display_start_date,
    CASE
        WHEN loan_due_date IS NOT NULL THEN loan_due_date
        ELSE reserved_due_date
    END AS display_due_date,
    CASE
        WHEN reserved_start_date IS NOT NULL AND reserved_by <> $5::uuid THEN TRUE
        ELSE FALSE
    END AS is_blocked_by_other_reservation,
    CASE
        WHEN reserved_start_date IS NOT NULL AND reserved_by = $5::uuid THEN TRUE
        ELSE FALSE
    END AS is_reserved_by_me
FROM tool_state
WHERE
    (
        $6::text = ''
        OR (
            CASE
                WHEN base_status = 'BROKEN' THEN 'BROKEN'
                WHEN base_status = 'REPAIR' THEN 'REPAIR'
                WHEN loan_start_date IS NOT NULL THEN 'LOANED'
                WHEN reserved_start_date IS NOT NULL THEN 'RESERVED'
                ELSE 'AVAILABLE'
            END = $6::text
        )
    )
ORDER BY asset_no ASC
LIMIT $7 OFFSET $8
`

type ListToolsWithDisplayParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 string    `json:"column_4"`
	Column5 uuid.UUID `json:"column_5"`
	Column6 string    `json:"column_6"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListToolsWithDisplayRow struct {
	ID                          uuid.UUID   `json:"id"`
	AssetNo                     string      `json:"asset_no"`
	Name                        string      `json:"name"`
	WarehouseID                 uuid.UUID   `json:"warehouse_id"`
	WarehouseName               string      `json:"warehouse_name"`
	BaseStatus                  string      `json:"base_status"`
	DisplayStatus               string      `json:"display_status"`
	DisplayStartDate            interface{} `json:"display_start_date"`
	DisplayDueDate              interface{} `json:"display_due_date"`
	IsBlockedByOtherReservation bool        `json:"is_blocked_by_other_reservation"`
	IsReservedByMe              bool        `json:"is_reserved_by_me"`
}

func (q *Queries) ListToolsWithDisplay(ctx context.Context, arg ListToolsWithDisplayParams) ([]ListToolsWithDisplayRow, error) {
	rows, err := q.db.QueryContext(ctx, listToolsWithDisplay,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolsWithDisplayRow{}
	for rows.Next() {
		var i ListToolsWithDisplayRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetNo,
			&i.Name,
			&i.WarehouseID,
			&i.WarehouseName,
			&i.BaseStatus,
			&i.DisplayStatus,
			&i.DisplayStartDate,
			&i.DisplayDueDate,
			&i.IsBlockedByOtherReservation,
			&i.IsReservedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTool = `-- name: UpdateTool :one
UPDATE tools
SET name = $2,
    warehouse_id = $3,
    base_status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, asset_no, name, warehouse_id, base_status, created_at, updated_at
`

type UpdateToolParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	WarehouseID uuid.UUID `json:"warehouse_id"`
	BaseStatus  string    `json:"base_status"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error) {
	row := q.db.QueryRowContext(ctx, updateTool,
		arg.ID,
		arg.Name,
		arg.WarehouseID,
		arg.BaseStatus,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.WarehouseID,
		&i.BaseStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
