// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    role,
    department,
    username,
    email,
    password_hash,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    TRUE,
    NOW(),
    NOW()
)
RETURNING id, role, department, username, email, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Role         string `json:"role"`
	Department   string `json:"department"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID         uuid.UUID `json:"id"`
	Role       string    `json:"role"`
	Department string    `json:"department"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Role,
		arg.Department,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Department,
		&i.Username,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, department, username, email, is_active
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         uuid.UUID `json:"id"`
	Role       string    `json:"role"`
	Department string    `json:"department"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	IsActive   bool      `json:"is_active"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Department,
		&i.Username,
		&i.Email,
		&i.IsActive,
	)
	return i, err
}

const getUserByLoginID = `-- name: GetUserByLoginID :one
SELECT id, role, department, username, email, password_hash, is_active
FROM users
WHERE email = $1 OR username = $1
LIMIT 1
`

type GetUserByLoginIDRow struct {
	ID           uuid.UUID `json:"id"`
	Role         string    `json:"role"`
	Department   string    `json:"department"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) GetUserByLoginID(ctx context.Context, email string) (GetUserByLoginIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByLoginID, email)
	var i GetUserByLoginIDRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Department,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const listAdminEmails = `-- name: ListAdminEmails :many
SELECT email
FROM users
WHERE role = 'admin' AND is_active = TRUE
ORDER BY created_at
`

func (q *Queries) ListAdminEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAdminEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForUpdate = `-- name: LockUserForUpdate :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, lockUserForUpdate, id)
	err := row.Scan(&id)
	return id, err
}
