// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: warehouses.sql

package sqlc

import (
	"context"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (
    name,
    created_at,
    updated_at
) VALUES (
    $1,
    NOW(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWarehouse(ctx context.Context, name string) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, createWarehouse, name)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, name, created_at, updated_at
FROM warehouses
ORDER BY name ASC
`

func (q *Queries) ListWarehouses(ctx context.Context) ([]Warehouse, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
