DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS loan_items;
DROP TABLE IF EXISTS loan_boxes;
DROP TABLE IF EXISTS tools;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS btree_gist;
DROP EXTENSION IF EXISTS pgcrypto;
